services:
  db:
    container_name: mysqlDB
    image: "mysql:8.2.0"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./env/db.env
  app:
    container_name: goApp
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh:ro # ホストの~/.sshディレクトリをコンテナの/root/.sshに読み取り専用でマウント
      - ~/.gitconfig:/root/.gitconfig:ro # ホストの~/.gitconfigをコンテナに読み取り専用でマウント
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    env_file:
      - ./env/app.env
    depends_on:
      - db
volumes:
  db_data:
